name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/machikado-network/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: question
          label-operator: NOT
