name: Release sakura CLI
on:
  push:
    branches-ignore:
      - '**'

    tags:
      - 'v*'
jobs:
  build-sakura-cli:
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf]
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Get the tag
        id: tag
        run: echo "name=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: build
        run: |
          cross build --verbose --target ${{ matrix.target }} --release

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.tag.outputs.name }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/sakura

  draft-release-sakura-cli:
    needs: [build-sakura-cli]
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.draft-release.outputs.upload_url }}
    steps:
      - name: Get the tag
        id: tag
        run: echo "name=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Create a draft release
        id: draft-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: ${{ steps.tag.outputs.name }}
          release_name: ${{ steps.tag.outputs.name }}
          body: |
            ## Changelog
          draft: true
          prerelease: false

  upload-artifacts:
    strategy:
      matrix:
        target: [aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf]
    needs: [ build-sakura-cli, draft-release-sakura-cli ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the tag
        id: tag
        run: echo "name=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v1
        with:
          name: ${{ steps.tag.outputs.name }}-${{ matrix.target }}

      - name: Show Files
        run: ls -R

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.draft-release-sakura-cli.outputs.upload_url }}
          asset_path: ./${{ steps.tag.outputs.name }}-${{ matrix.target }}/sakura
          asset_name: ${{ steps.tag.outputs.name }}-${{ matrix.target }}
          asset_content_type: application/octet-stream
